# --- General Settings ---
set -g default-terminal "screen-256color"
set -g history-limit 10000
set -g mouse on
setw -g mode-keys vi
set -g allow-passthrough on
set -as terminal-features ',xterm-256color:clipboard'
set -as terminal-features ",*:hyperlinks"
set -s set-clipboard on

# --- Key Bindings ---
# Reload config
bind r source-file ~/.tmux.conf \; display "Config reloaded!"

# Vim-style pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Change prefix from C-b to C-a
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Copy mode settings
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -selection clipboard -i"

# --- UI / Status Bar ---
setw -g clock-mode-style 24
set -g status-left-length 40
set -g status-right "#(date -u +%%Y-%%m-%%dT%%H:%%M:%%S.%%3NZ)"
set -g status-interval 1
